<?php
echo '';
echo '';
echo '<html>';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="description" content="[!] BIKS ON TOP[!]">';
echo '<meta name="keywords" content="[!] BIKS ON TOP [!]">';
echo '<meta http-equiv="cache-control" content="index,cache">';
echo '<meta http-equiv="pragma" content="index,cache">';
echo '<meta name="theme-color" content="black">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<link rel="preload" as="image/png" href="Tod">';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">';
echo '<link rel="icon" href="https://k.top4top.io/p_28770oqec0.jpg">';
echo '<link href="https://fonts.googleapis.com/css2?family=Courier+Prime&amp;family=Roboto&amp;family=Roboto+Mono&amp;display=swap" rel="stylesheet">';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">';
echo '<link href="https://fonts.googleapis.com/css2?family=Exo+2&amp;family=Josefin+Sans&amp;display=swap" rel="stylesheet">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<script type="text/javascript">';
echo '';
echo '';
echo '';
echo 'aud01.play()';
echo '';
echo 'var viewMode = getCookie("view-mode");';
echo '';
echo 'if (viewMode == "desktop") {';
echo '';
echo 'viewport.setAttribute("content", "width=1024");';
echo '';
echo '} else if (viewMode == "mobile") {';
echo '';
echo 'viewport.setAttribute(';
echo '';
echo '"content",';
echo '';
echo '"width=device-width, initial-scale=1.0,maximum-scale=1.0,user-scalable=no"';
echo '';
echo ');';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '</script>';
echo '<style>';
echo '';
echo '@import url('https://fonts.googleapis.com/css2?family=Exo+2&family=Josefin+Sans&display=swap');';
echo '';
echo '@import url('https://fonts.googleapis.com/css2?family=Courier+Prime&family=Roboto&family=Roboto+Mono&display=swap');';
echo '';
echo ':root{';
echo '';
echo '--white: #FFFFFF;';
echo '';
echo '--img: invert(0%) sepia(0%) saturate(9%) hue-rotate(204deg) brightness(108%) contrast(103%);';
echo '';
echo '}';
echo '';
echo '.parent {';
echo '';
echo 'display: flex;';
echo '';
echo 'justify-content: center;';
echo '';
echo 'align-items: center;';
echo '';
echo '}';
echo '';
echo 'img {';
echo '';
echo 'margin-left: auto;';
echo '';
echo 'margin-right: auto;';
echo '';
echo 'justify-content: center;';
echo '';
echo 'align-items: center;';
echo '';
echo 'transition: filter 0.5s;';
echo '';
echo 'overflow: hidden;';
echo '';
echo '}';
echo '';
echo '.texts{';
echo '';
echo 'margin:auto;';
echo '';
echo 'color: var(--white);';
echo '';
echo 'font-family: 'Josefin Sans', sans-serif;';
echo '';
echo '}';
echo '';
echo '.texts2{';
echo '';
echo 'margin:auto;';
echo '';
echo 'color: var(--white);';
echo '';
echo 'font-weight:bolder;';
echo '';
echo 'font-family: sans-serif;';
echo '';
echo 'opacity: 50%;';
echo '';
echo '}';
echo '';
echo '.texts3{';
echo '';
echo 'margin:auto;';
echo '';
echo '';
echo '';
echo 'font-family: 'Courier Prime', monospace;';
echo '';
echo '}';
echo '';
echo 'html, body{';
echo '';
echo 'height: 100%;';
echo '';
echo 'margin:0;';
echo '';
echo 'padding:0;';
echo '';
echo 'overflow:hidden;';
echo '';
echo '}';
echo '';
echo '.container{';
echo '';
echo 'display: flex;';
echo '';
echo 'justify-content: center;';
echo '';
echo 'height: 100%;';
echo '';
echo '}';
echo '';
echo '.middle{';
echo '';
echo 'display: flex;';
echo '';
echo 'align-items: center;';
echo '';
echo 'justify-content: center;';
echo '';
echo 'height: 100%;';
echo '';
echo '}';
echo '';
echo '.cusbtn {';
echo '';
echo 'content: ' ';';
echo '';
echo 'background-color: #4caf4f00;';
echo '';
echo 'border: 0.1rem solid var(--white);';
echo '';
echo 'color: var(--white);';
echo '';
echo 'padding: 10px 27px;';
echo '';
echo 'text-align: center;';
echo '';
echo 'text-decoration: none;';
echo '';
echo 'display: inline-block;';
echo '';
echo 'font-size: 20px;';
echo '';
echo 'margin: 4px 2px;';
echo '';
echo 'cursor: pointer;';
echo '';
echo '}';
echo '';
echo '.boxborder {';
echo '';
echo 'border: 0.1rem solid var(--white);';
echo '';
echo 'padding: 0;';
echo '';
echo '}';
echo '';
echo '.drp {';
echo '';
echo 'font-size: 15px;';
echo '';
echo 'color: var(--white);';
echo '';
echo 'background: #000000;';
echo '';
echo 'font-family: 'Roboto', sans-serif;';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '.type {';
echo '';
echo 'display:inline-block;';
echo '';
echo '';
echo '';
echo 'vertical-align: bottom;';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '.type > span {';
echo '';
echo 'color: #14f3db;';
echo '';
echo 'display:grid;';
echo '';
echo 'overflow: hidden;';
echo '';
echo 'height:1.2em;';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '.type span span {';
echo '';
echo 'width:0%;';
echo '';
echo 'line-height: 1.7;';
echo '';
echo 'max-width:max-content;';
echo '';
echo 'overflow: hidden;';
echo '';
echo 'height:inherit;';
echo '';
echo 'word-break:break-all;';
echo '';
echo 'animation:';
echo '';
echo 't 2s linear infinite alternate,';
echo '';
echo 'm 12s steps(3) infinite;';
echo '';
echo '}';
echo '';
echo '.type span span:before {';
echo '';
echo 'content:" ";';
echo '';
echo 'display:inline-block;';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '@keyframes t{';
echo '';
echo '90%,100% {width:100%}';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '@keyframes c{';
echo '';
echo '0%,100%{box-shadow:3px 0 0 #0000}';
echo '';
echo '50%{box-shadow:3px 0 0 white}';
echo '';
echo '';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '@keyframes m{';
echo '';
echo '100% {transform:translateY(-300%)}';
echo '';
echo '}';
echo '';
echo '}';
echo '';
echo '</style>';
echo '<title>Recovered by BIKS</title>';
echo '</head>';
echo '<body bgcolor="black" onload="display_ct7();" scroll="no" style="overflow: hidden">';
echo '<script type="text/javascript">';
echo '';
echo 'function display_ct7() {';
echo '';
echo 'var x = new Date()';
echo '';
echo 'var ampm = x.getHours( ) >= 12 ? ' PM' : ' AM';';
echo '';
echo 'hours = x.getHours( );';
echo '';
echo 'hours = hours ? hours : 12;';
echo '';
echo 'hours=hours.toString().length==1? 0+hours.toString() : hours;';
echo '';
echo '';
echo '';
echo 'var minutes=x.getMinutes().toString()';
echo '';
echo 'minutes=minutes.length==1 ? 0+minutes : minutes;';
echo '';
echo '';
echo '';
echo 'var seconds=x.getSeconds().toString()';
echo '';
echo 'seconds=seconds.length==1 ? 0+seconds : seconds;';
echo '';
echo '';
echo '';
echo 'var month=(x.getMonth() +1).toString();';
echo '';
echo 'month=month.length==1 ? 0+month : month;';
echo '';
echo '';
echo '';
echo 'var dt=x.getDate().toString();';
echo '';
echo 'dt=dt.length==1 ? 0+dt : dt;';
echo '';
echo '';
echo '';
echo 'var x1=month + "/" + dt + "/" + x.getFullYear();';
echo '';
echo 'x1 = x1 + " - " +  hours + ":" +  minutes + ":" +  seconds + " " + ampm;';
echo '';
echo 'document.getElementById('ct7').innerHTML = x1;';
echo '';
echo 'display_c7();';
echo '';
echo '}';
echo '';
echo 'function display_c7(){';
echo '';
echo 'var refresh=1000; // Refresh rate in milli seconds';
echo '';
echo 'mytime=setTimeout('display_ct7()',refresh)';
echo '';
echo '}';
echo '';
echo 'display_c7();';
echo '';
echo '</script>';
echo '<script type="text/javascript">';
echo '';
echo 'var snowmax=40';
echo '';
echo 'var snowcolor=new Array("#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF")';
echo '';
echo 'var snowtype=new Array("Arial Black","Arial Narrow","Times","Comic Sans MS")';
echo '';
echo 'var snowletter=""';
echo '';
echo 'var sinkspeed=0.6';
echo '';
echo 'var snowmaxsize=15';
echo '';
echo 'var snowminsize=8';
echo '';
echo 'var snowingzone=1';
echo '';
echo '';
echo '';
echo '// Do not edit below this line';
echo '';
echo 'var snow=new Array()';
echo '';
echo 'var marginbottom';
echo '';
echo 'var marginright';
echo '';
echo 'var timer';
echo '';
echo 'var i_snow=0';
echo '';
echo 'var x_mv=new Array();';
echo '';
echo 'var crds=new Array();';
echo '';
echo 'var lftrght=new Array();';
echo '';
echo 'var browserinfos=navigator.userAgent';
echo '';
echo 'var ie5=document.all&&document.getElementById&&!browserinfos.match(/Opera/)';
echo '';
echo 'var ns6=document.getElementById&&!document.all';
echo '';
echo 'var opera=browserinfos.match(/Opera/)';
echo '';
echo 'var browserok=ie5||ns6||opera';
echo '';
echo '';
echo '';
echo 'function randommaker(range) {';
echo '';
echo 'rand=Math.floor(range*Math.random())';
echo '';
echo 'return rand';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'function initsnow() {';
echo '';
echo 'if (ie5 || opera) {';
echo '';
echo 'marginbottom = document.body.clientHeight';
echo '';
echo 'marginright = document.body.clientWidth';
echo '';
echo '}';
echo '';
echo 'else if (ns6) {';
echo '';
echo 'marginbottom = window.innerHeight';
echo '';
echo 'marginright = window.innerWidth';
echo '';
echo '}';
echo '';
echo 'var snowsizerange=snowmaxsize-snowminsize';
echo '';
echo 'for (i=0;i<=snowmax;i++) {';
echo '';
echo 'crds[i] = 0;';
echo '';
echo 'lftrght[i] = Math.random()*15;';
echo '';
echo 'x_mv[i] = 0.03 + Math.random()/10;';
echo '';
echo 'snow[i]=document.getElementById("s"+i)';
echo '';
echo 'snow[i].style.fontFamily=snowtype[randommaker(snowtype.length)]';
echo '';
echo 'snow[i].size=randommaker(snowsizerange)+snowminsize';
echo '';
echo 'snow[i].style.fontSize=snow[i].size';
echo '';
echo 'snow[i].style.color=snowcolor[randommaker(snowcolor.length)]';
echo '';
echo 'snow[i].sink=sinkspeed*snow[i].size/5';
echo '';
echo 'if (snowingzone==1) {snow[i].posx=randommaker(marginright-snow[i].size)}';
echo '';
echo 'if (snowingzone==2) {snow[i].posx=randommaker(marginright/2-snow[i].size)}';
echo '';
echo 'if (snowingzone==3) {snow[i].posx=randommaker(marginright/2-snow[i].size)+marginright/4}';
echo '';
echo 'if (snowingzone==4) {snow[i].posx=randommaker(marginright/2-snow[i].size)+marginright/2}';
echo '';
echo 'snow[i].posy=randommaker(2*marginbottom-marginbottom-2*snow[i].size)';
echo '';
echo 'snow[i].style.left=snow[i].posx';
echo '';
echo 'snow[i].style.top=snow[i].posy';
echo '';
echo '}';
echo '';
echo 'movesnow()';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'function movesnow() {';
echo '';
echo 'for (i=0;i<=snowmax;i++) {';
echo '';
echo 'crds[i] += x_mv[i];';
echo '';
echo 'snow[i].posy+=snow[i].sink';
echo '';
echo 'snow[i].style.left=snow[i].posx+lftrght[i]*Math.sin(crds[i]);';
echo '';
echo 'snow[i].style.top=snow[i].posy';
echo '';
echo '';
echo '';
echo 'if (snow[i].posy>=marginbottom-2*snow[i].size || parseInt(snow[i].style.left)>(marginright-3*lftrght[i])){';
echo '';
echo 'if (snowingzone==1) {snow[i].posx=randommaker(marginright-snow[i].size)}';
echo '';
echo 'if (snowingzone==2) {snow[i].posx=randommaker(marginright/2-snow[i].size)}';
echo '';
echo 'if (snowingzone==3) {snow[i].posx=randommaker(marginright/2-snow[i].size)+marginright/4}';
echo '';
echo 'if (snowingzone==4) {snow[i].posx=randommaker(marginright/2-snow[i].size)+marginright/2}';
echo '';
echo 'snow[i].posy=0';
echo '';
echo '}';
echo '';
echo '}';
echo '';
echo 'var timer=setTimeout("movesnow()",50)';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'for (i=0;i<=snowmax;i++) {';
echo '';
echo 'document.write("<span id='s"+i+"' style='position:absolute;top:-"+snowmaxsize+"'>"+snowletter+"</span>")';
echo '';
echo '}';
echo '';
echo 'if (browserok) {';
echo '';
echo 'window.onload=initsnow';
echo '';
echo '}';
echo '';
echo '</script>';
echo '<div class="container" style="min-height: 100%;">';
echo '<div class="middle" style="min-height: 100%;">';
echo '<div style="text-align: center; width:1000px; top:5%;">';
echo '<img src="https://media.tenor.com/YB58oQ8Xj0oAAAAC/anime-sad-anime.gif" alt="Fucking" width="400" height="200" border="0">';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<font size="6" class="texts"><span style="opacity: 50%;">[+]---</span><span style="font-weight:bold;"> Recovered by BIKS !!!</span><span style="opacity: 50%;">---[+]</span></font>';
echo '<div class="texts2" style="margin:auto; margin-top:10px; background-color:var(--white); width: 300px; height: 3px;"></div>';
echo '<br>';
echo '<font size="5" class="texts3" color="white"><span>BIKS</span></font>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<font size="6" class="texts3" color="red">“ Fuck Bangladesh ”</font><br><font size="6" class="texts3" color="white">THIS WEBSITE WAS HACKED BY SOME BD HACKER AND RECOVERED BY BIKS ( ANONYMOUS NEPAL )</font><br> <font size="5" class="texts3" color="white" style="opacity: 50%;"><br><br><i>– [!] THANKS TO MY KEYBOARD[!] –</i></font>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<div class="texts2" style="margin:auto; background-color:var(--white); width: 830px; height: 3px;"></div>';
echo '<div class="parent" align="center" style="margin:auto; width: 850px; height: 25px;">';
echo '<font size="6" class="texts2">||</font>';
echo '<font class="texts" size="5" style=" font-weight:bold; margin-top:10px;"> Greetz </font>';
echo '<font size="6" class="texts2">:</font>';
echo '<div class="parent" align="center" style="width: 650px; height: 25px;">';
echo '<font size="5" style="font-weight:bold; margin-top:10px;" class="texts">';
echo '<marquee>';
echo '</> BIKS';
echo '</marquee> </font>';
echo '</div>';
echo '<font size="6" class="texts2">||</font>';
echo '</div>';
echo '<br>';
echo '<div class="texts2" style="margin:auto; background-color:var(--white); width: 830px; height: 3px;"></div>';
echo '<br>';
echo '<div class="boxborder parent" align="center" style="margin:auto; width: 400px; height: 40px;">';
echo '<div class="parent" align="center" style="margin:auto; width: 395px; height: 30px;">';
echo '<select class="cusbtn select" name="audios" id="audios" style=" padding: 0px 0px; width:30px; height:30px; font-size: 15px; margin-left: 2px;" title="Audio Library"> <option class="drp" value="01">| DJ AS IF IT'S YOUR LAST |</option> <option class="drp" value="02">| reckless speed up |</option> <option class="drp" value="04">| DJ KARENA BERSAMAMU TERASA INDAH |</option> <option class="drp" value="05">| DJ BASTA BOI |</option> </select>';
echo '<button class="cusbtn" id="play" onclick="play()" style="width:30px; height:30px; padding: 0px 0px; font-size: 20px; margin-right: 2px; margin-left: 2px;" title="Play Audio"><i class="fa fa-play-circle"></i></button>';
echo '<button class="cusbtn" id="pause" onclick="pause()" style="opacity:50%; width:30px; height:30px; padding: 0px 0px; font-size: 20px; margin-right: 2px; margin-left: 2px;" title="Pause Audio"><i class="fa fa-stop-circle"></i></button>';
echo '<button id="looptrue" class="cusbtn" onclick="looptrue()" style="width:30px; height:30px; padding: 0px 0px;" title="Repeat OFF"><i class="fa fa-retweet" style="color: #FFFFFF;"></i></button>';
echo '<button id="loopfalse" class="cusbtn" onclick="loopfalse()" style="opacity:50%; width:30px; height:30px; padding: 0px 0px;" title="Repeat ON"><i class="fa fa-retweet" style="color: #FFFFFF;"></i></button>';
echo '<div class="boxborder parent" align="center" style="margin:auto; width: 240px; height: 17px; padding: 5px; margin-right: 2px; margin-left: 2px; overflow: hidden;">';
echo '<span class="type line-height: 1.6;"> <span style="background-color: #000000; margin:auto; height: 20px;"> <span size="4" style="font-weight: bold; height: 30px;" class="texts">Now Playing:</span> <span size="3" style="font-weight: bold; height: 30px;" class="texts" id="title">NOTHING</span> <span size="4" style="font-weight: bold; height: 30px;" class="texts">RECOVERED BY BIKS </span> </span> </span>';
echo '</div>';
echo '<div class="boxborder" align="center" style="margin:auto; width: 50px; height: 17px; padding: 5px; margin-right: 2px; margin-left: 2px;">';
echo '<font id="timeleft" class="texts" style="font-weight: bold; font-family: 'Roboto Mono';" size="2">00:00</font>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<br>';
echo '<font id="ct7" size="5" class="texts" style="opacity: 50%; color: var(--white); font-family: 'Roboto Mono', monospace;"></font>';
echo '<br>';
echo '<br>';
echo '<font size="4" class="texts" style="opacity: 50%; color: var(--white); font-family: 'Roboto Mono', monospace;">Copyrights © biks </font> l';
echo '<audio id="aud01" src="https://h.top4top.io/m_28955klk22.mp3"></audio>';
echo '<audio id="aud02" src="https://j.top4top.io/m_2578q39ld0.mp4"></audio>';
echo '<audio id="aud04" src="https://k.top4top.io/m_2894x57ip0.mp3"></audio>';
echo '<audio id="aud05" src="https://f.top4top.io/m_2566al6jq1.mp3"></audio>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<script type="text/javascript">';
echo '';
echo '';
echo '';
echo '';
echo '';
echo 'var Audloop = 0;';
echo '';
echo 'paragraph = document.getElementById("title");';
echo '';
echo 'document.getElementById("audios").onchange = function() {title()};';
echo '';
echo '';
echo '';
echo 'function title()';
echo '';
echo '{';
echo '';
echo 'var x = document.getElementById("audios").value;';
echo '';
echo 'if(x == 01){';
echo '';
echo 'paragraph.innerHTML = "DJ AS IF IT'S YOUR LAST";';
echo '';
echo '}';
echo '';
echo 'else if(x == 02){';
echo '';
echo 'paragraph.innerHTML = "reckless speed up";';
echo '';
echo '}';
echo '';
echo 'else if(x == 03){';
echo '';
echo 'paragraph.innerHTML = "DJ KARENA BERSAMAMU TERASA INDAH";';
echo '';
echo '}';
echo '';
echo 'else if(x == 04){';
echo '';
echo 'paragraph.innerHTML = "DJ KARENA BERSAMAMU TERASA INDAH";';
echo '';
echo '}';
echo '';
echo 'else if(x == 05){';
echo '';
echo 'paragraph.innerHTML = "DJ BASTA BOI";';
echo '';
echo '}';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'const looptrue = document.getElementById('looptrue');';
echo '';
echo 'const loopfalse = document.getElementById('loopfalse');';
echo '';
echo '';
echo '';
echo 'loopfalse.style.display = 'none';';
echo '';
echo '';
echo '';
echo 'looptrue.addEventListener('click', () => {';
echo '';
echo 'looptrue.style.display = 'none';';
echo '';
echo 'loopfalse.style.display = 'block';';
echo '';
echo 'Audloop = 1;';
echo '';
echo '});';
echo '';
echo '';
echo '';
echo 'loopfalse.addEventListener('click', () => {';
echo '';
echo 'looptrue.style.display = 'block';';
echo '';
echo 'loopfalse.style.display = 'none';';
echo '';
echo 'Audloop = 0;';
echo '';
echo '});';
echo '';
echo '';
echo '';
echo '';
echo '';
echo 'document.getElementById('pause').style.display = 'none';';
echo '';
echo '';
echo '';
echo '';
echo '';
echo 'document.querySelectorAll('audio').forEach(el => el.addEventListener('ended', function (e) {';
echo '';
echo 'document.getElementById('pause').style.display = 'none';';
echo '';
echo 'document.getElementById('play').style.display = 'block';';
echo '';
echo 'var endedTag=e.target;';
echo '';
echo '}));';
echo '';
echo '';
echo '';
echo 'function pause() {';
echo '';
echo '';
echo '';
echo 'document.getElementById('pause').style.display = 'none';';
echo '';
echo 'document.getElementById('play').style.display = 'block';';
echo '';
echo 'document.querySelectorAll('audio').forEach(el => el.pause());';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'function timeLeft(player) {';
echo '';
echo 'var aud = document.getElementById(player);';
echo '';
echo '// Countdown';
echo '';
echo 'aud.addEventListener("timeupdate", function() {';
echo '';
echo 'var timeleft = document.getElementById('timeleft'),';
echo '';
echo 'duration = parseInt( aud.duration ),';
echo '';
echo 'currentTime = parseInt( aud.currentTime ),';
echo '';
echo 'timeLeft = duration - currentTime,';
echo '';
echo 's, m;';
echo '';
echo '';
echo '';
echo '';
echo '';
echo 's = timeLeft % 60;';
echo '';
echo 'm = Math.floor( timeLeft / 60 ) % 60;';
echo '';
echo '';
echo '';
echo 's = s < 10 ? "0"+s : s;';
echo '';
echo 'm = m < 10 ? "0"+m : m;';
echo '';
echo '';
echo '';
echo 'timeleft.innerHTML = m+":"+s;';
echo '';
echo '';
echo '';
echo '}, false);';
echo '';
echo '';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'function play() {';
echo '';
echo 'document.getElementById('pause').style.display = 'block';';
echo '';
echo 'document.getElementById('play').style.display = 'none';';
echo '';
echo '';
echo '';
echo 'var Aud = document.getElementById("audios").value;';
echo '';
echo 'var aud01 = document.getElementById("aud01");';
echo '';
echo 'var aud02 = document.getElementById("aud02");';
echo '';
echo 'var aud03 = document.getElementById("aud03");';
echo '';
echo 'var aud04 = document.getElementById("aud04");';
echo '';
echo 'var aud05 = document.getElementById("aud05");';
echo '';
echo '';
echo '';
echo 'if(Aud==01){';
echo '';
echo 'title()';
echo '';
echo 'aud01.play();';
echo '';
echo 'aud01.currentTime = 0;';
echo '';
echo 'timeLeft("aud01")';
echo '';
echo 'if(Audloop == 1){';
echo '';
echo 'aud01.loop = true;';
echo '';
echo 'timeLeft("aud01")';
echo '';
echo '}else if(Audloop == 0){ aud01.loop = false; };';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'else if(Aud==02){';
echo '';
echo 'title()';
echo '';
echo 'aud02.play();';
echo '';
echo 'aud02.currentTime = 0;';
echo '';
echo 'timeLeft("aud02")';
echo '';
echo 'if(Audloop == 1){';
echo '';
echo 'aud02.loop = true;';
echo '';
echo 'timeLeft("aud02")';
echo '';
echo '}else if(Audloop == 0){ aud02.loop = false; };';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'else if(Aud==03){';
echo '';
echo 'title()';
echo '';
echo 'aud03.play();';
echo '';
echo 'aud03.currentTime = 0;';
echo '';
echo 'timeLeft("aud03")';
echo '';
echo 'if(Audloop == 1){';
echo '';
echo 'aud03.loop = true;';
echo '';
echo 'timeLeft("aud03")';
echo '';
echo '}else if(Audloop == 0){ aud03.loop = false; };';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo 'else if(Aud==04){';
echo '';
echo 'title()';
echo '';
echo 'aud04.play();';
echo '';
echo 'aud04.currentTime = 0;';
echo '';
echo 'timeLeft("aud04")';
echo '';
echo 'if(Audloop == 1){';
echo '';
echo 'aud04.loop = true;';
echo '';
echo 'timeLeft("aud04")';
echo '';
echo '}else if(Audloop == 0){ aud04.loop = false; };';
echo '';
echo '}';
echo '';
echo 'else if(Aud==05){';
echo '';
echo 'title()';
echo '';
echo 'aud05.play();';
echo '';
echo 'aud05.currentTime = 0;';
echo '';
echo 'timeLeft("aud05")';
echo '';
echo 'if(Audloop == 1){';
echo '';
echo 'aud05.loop = true;';
echo '';
echo 'timeLeft("aud05")';
echo '';
echo '}else if(Audloop == 0){ aud05.loop = false; };';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '}';
echo '';
echo '';
echo '';
echo '</script> " target="_blank"&gt;';
echo '</body>';
echo '</html>';
echo '<DOCYPE html>';
echo '';
echo '';
echo '';
?>